logistic/bills/urls.py
from django.conf.urls import url
from . import views

app_name = 'bills'
urlpatterns = [
    # /bills/
    url(r'^$', views.IndexView.as_view(), name="index"),
    url(r'^upload_file/$', views.UploadFile.as_view(), name="upload_file"),
    url(r'^delete_file/(?P<pk>[0-9]+)$', views.FileDelete.as_view(), name='delete_file'),
    url(r'^update_file/(?P<pk>[0-9]+)$', views.UpdateFile.as_view(), name='update_file'),
]

logistic/logistic/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('bills.urls')),

]

logistic/bills/models.py
from django.db import models
from django.db import models
from jsonfield import JSONField
from collections import OrderedDict


# Create your models here.
#Manage Excel Files
class File(models.Model):
    file_file = models.FileField(default='')
    thumbnail = models.CharField(max_length=250, default='https://www.mathworks.com/matlabcentral/mlc-downloads/downloads/submissions/48551/versions/6/screenshot.jpg')
#Store and retrieve Json Data
class Data(models.Model):
    json= JSONField(load_kwargs={'object_pairs_hook': OrderedDict})

logistic/bills/forms.py
from django import forms
from .models import File

class FileForm(forms.ModelForm):

    class Meta:
        model = File
        fields = ['file_file', 'thumbnail']

logistic/bills/views.py
from django.conf.global_settings import MEDIA_ROOT
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView,View
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.auth.decorators import user_passes_test
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from .models import File
from . import clasify as cla
import os

# Create your views here.

class IndexView(ListView):
    context_object_name = 'Files'
    template_name = 'bills/index.html'
    queryset = File.objects.all()
    file_path = os.path.join(MEDIA_ROOT,'DATOS.xlsx') or None


    def get_context_data(self, **kwargs):
        context = super(IndexView, self).get_context_data(**kwargs)
        try:

            context['file_list'] = File.objects.all()
            context['count_rows'] = File.objects.count()
            context['clasification_table']=cla.data_clasification(self.file_path)
            context['content_table']=cla.list_of_list(self.file_path)
            context['table_header'] = cla.table_head(self.file_path)
        except:
            print("Filepath is None")
            #context['content_table'] = None
            #context['table_header'] = None
        return context

#File Uploading

class UploadFile(CreateView):
    model = File
    template_name = 'bills/upload-file.html'
    fields=['file_file','thumbnail']
    success_url = reverse_lazy('bills:index')
#File Delete
class FileDelete(DeleteView):
    redirect_field_name = 'redirect_to'
    model = File
    success_url = reverse_lazy('bills:index')

class UpdateFile(UpdateView):
    redirect_file_name='redirect_to'
    model=File
    success_url = reverse_lazy('bills:index')
    fields=['file_file','thumbnail']
    template_name = 'bills/upload-file.html'

    # def form_valid(self, form):
    #     object = form.save(commit=False)
    #     object.user = self.request.user
    #     object.save()
    #     return super(UpdateFile, self).form_valid(form)

logistic/bills/templates/base.html
<!DOCTYPE html>
<html lang="en">
{% load staticfiles %}
<head>
    <meta charset="UTF-8">
    <title>LOGISTIC IA</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <link href="https://fonts.googleapis.com/css?family=Amaranth:400i" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Kalam:700" rel="stylesheet">
    <link href="{% static 'style.css' %}" type="text/css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Ubuntu+Mono:700i" rel="stylesheet">
    <script src="https://maps.googleapis.com/maps/api/js?v=3.exp&key=AIzaSyCiQYTNub53NHbde4y56ID6Ro8K7m3avZE"></script>

</head>
<body>

    <!-- Header -->
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container-field">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url 'bills:index' %}"><span class="glyphicon glyphicon-home" aria-hidden="true">  </span>
                    Logistic Intelligent Asistant  </a>
            </div>
            <!-- Items -->
            <div class="collapse navbar-collapse" id="topNavBar">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </nav>

    {% block body %}
    {% endblock %}

<script src="{% static 'main.js' %}"></script>
<script src="{% static 'TweenLite.min.js' %}"></script>
<script src="{% static 'EasePack.min.js' %}"></script>
<script src="{% static 'rAF.js' %}"></script>
<script src="{% static 'animation.js' %}"></script>

</body>
</html>

logistic/bills/templates/bills/index.html
{% extends 'base.html' %}
{% block body %}
        <div id="large-header" class="large-header">
<canvas id="demo-canvas"></canvas>
    <div class="container body">
        <div class="col-lg-18">
            <div class="father">
                <div class="col-sm-8">
                    <ul><h3>FEATURES </h3>
                        <li><h4>Ms. Excel. Data reading</h4></li>
                        <li><h4>Dinamic data content</h4></li>
                        <li><h4>Intelligent operator clasification</h4></li>
                        <li><h4>Optimal dispatch generation</h4></li>
                        <li><h4>Intelligent routes optimization</h4></li>
                    </ul>
                </div><div class="col-sm-4">
                <ul><h3>CREDITS </h3>
                    <li><h4>Cesar Ochoa</h4></li>
                </ul>
                <h2>Version 1.0</h2>
            </div>
            </div>
        </div>

        {% if count_rows < 1 %}
        <a href="{% url 'bills:upload_file' %}">
            <button type="button" class="btn btn-default" role="button"><span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Upload </button>
        </a>
        <p>*Remember, your Excel file has to be named "DATOS.xlsx"</p>


        {% else %}
        {% if file_list %}
        <ul id="home_list_1">
            <li >
                <div class="col-sm-2">
                    <div class="panel panel-default" style="text-align: center">
                        <div class="panel-body">
                            <h3>Training Data</h3>
                            <div class="thumbnail">
                                <a href="{% url 'bills:index' %}">
                                    <img src="{{ file_list.0.thumbnail }}" class="img-responsive">
                                </a>
                            </div>
                            <div class="caption">
                                <form action="{% url 'bills:update_file' file_list.0.id %}" method="post" style="display: inline;">
                                    {% csrf_token %}
                                    <input type="hidden" name="file.id" value="{{ file_list.0.id }}" />
                                    <button type="submit" class="btn btn-default btn-sm">
                                        <span class="glyphicon glyphicon-File"></span> Update File
                                    </button>
                                </form>
                                <h5></h5>
                                <form action="{% url 'bills:delete_file' file_list.0.id %}" method="post" style="display: inline;">
                                    {% csrf_token %}
                                    <input type="hidden" name="file.id" value="{{ file_list.0.id }}" />
                                    <button type="submit" class="btn btn-default btn-sm">
                                        <span class="glyphicon glyphicon-trash"></span> Delete File
                                    </button>
                                </form>

                            </div>
                        </div>

                    </div>
                </div>
            </li>
            {% if content_table %}
            <li>
                <div class="panel panel-default" id="spreadsheet">
                    <table class="table table-striped table-condensed">
                        <thead >
                        <tr><h3>Datos de Entrenamiento</h3></tr>
                        <tr>
                            {% for row in table_header %}
                            <td><h5>{{row}}</h5></td>
                            {% endfor %}
                        </tr>
                        </thead>
                        <tbody>
                        {% for attr in content_table %}
                        <tr>
                            {% for value in attr %}
                            <td>{{ value }}</td>
                            {% endfor %}
                        </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>

            </li>
            {% endif %}
        </ul>
        {% endif %}


        <div class="col-lg-12" >
            <button type="button" class="btn btn-dm" data-toggle="collapse" data-target="#spreadsheet1">Data Clasification</button>
            <button type="button" class="btn btn-dm" data-toggle="collapse" data-target="#cl-form">Single Row Clasification</button>
            <button type="button" class="btn btn-dm" data-toggle="collapse" data-target="#routes">View Routes On Map</button>

        </div>
        <div class="col-lg-12">

            <div class="panel panel-default collapse" id="spreadsheet1">

                    {% if clasification_table %}
                <script>
                    var table = {{ clasification_table|safe }};
                </script>
                    <table id="clas-table" class="table table-striped" >
                        <thead>
                        <tr>Datos Clasificados</tr>
                        <tr>
                            {% for row in table_header %}
                            <td><p>{{row}}</p></td>
                            {% endfor %}
                        </tr>
                        </thead>
                        <tbody >
                        {% for attr in clasification_table %}
                        <tr>
                            {% for value in attr %}
                            <td><p>{{ value }}</p></td>
                            {% endfor %}
                        </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                {% endif %}
            <button type="button" class="btn btn-dm" id="gen-dis">Generate Dispatch</button>
                </div>

        </div>
        <div class="col-lg-12">
            <div class="panel panel-default collapse" id="routes">
                <div class="panel-body">
                    <table class=" table table-striped" id="conf-table">
                        <tr>
                            <td colspan="2"><b>Configuration</b></td>
                        </tr>
                        <tr id="locate-button">
                            <td colspan="2">
                                <input id="add" type="text" placeholder="Write an address">
                                <button id="locate-dir" class="btn btn-sm">Locate Direction</button>
                            </td>
                        <tr>
                            <td><button id="get-dir" class="btn btn-default">Get Directions from Database</button></td>
                            <td><p>Status: </p><p id="get-status"></p>
                            </td>
                        </tr>
                        </tr>
                        <tr>
                            <td>Avoid Highways: </td>
                            <td>
                                <select id="avoid-highways">
                                    <option value="1">Enabled</option>
                                    <option value="0" selected="selected">Disabled</option>
                                </select>
                            </td>
                        </tr>
                        <tr>
                            <td>Elitism (Fast Mode):</td>
                            <td>
                                <select id="elitism">
                                    <option value="1" >Enabled</option>
                                    <option value="0" selected="selected">Disabled</option>
                                </select>
                            </td>
                        </tr>
                        <tr>
                            <td>Destinations Count: </td>
                            <td id="destinations-count">0</td>
                        </tr>
                        <tr class="ga-info" style="display:none;">
                            <td>Generations: </td><td id="generations-passed">0</td>
                        </tr>
                        <tr class="ga-info" style="display:none;">
                            <td>Best Time: </td><td id="best-time">?</td>
                        </tr>
                        <tr id="ga-buttons">
                            <td colspan="2"><button id="find-route" class="btn btn-default">Start</button> <button class="btn btn-default" id="clear-map">Clear</button></td>
                        </tr>
                    </table>
                    <div id="map-canvas" style="width:800px; height:550px; margin: 10px"></div>
                    <button type="button" class="btn btn-dm" id="reload-map" data-toggle="collapse" data-target="#routes">Reload the Map</button>
                </div>
            </div>
            <div class="panel panel-default collapse" id="cl-form" >
                <div class="panel-body">
                    <div class="clearfix">
                        <h3>Add Row</h3>
                        <form>
                            <div class="col-sm-6 form-row">
                                <input type="text" class="form-control" id="Factura" placeholder="Factura">
                            </div>
                            <div class="col-sm-6 form-row" >
                                <input type="text" class="form-control" id="Cliente" placeholder="Cliente">
                            </div>
                            <div class="col-sm-6 form-row">
                                <input type="text" class="form-control" id="Valor" placeholder="Valor Factura">
                            </div>
                            <div class="col-sm-6 form-row">
                                <input type="text" class="form-control" id="Fecha-Min" placeholder="Fecha Mínima">
                            </div>
                            <div class="col-sm-6 form-row">
                                <input type="text" class="form-control" id="Fecha-Max" placeholder="Fecha Máxima">
                            </div>
                            <div class="col-sm-6 form-row">
                                <input type="text" class="form-control" id="Dirección" placeholder="Dirección">
                            </div>
                            <button type="button" id="contact_submit" class="btn btn-dm">Add Row</button>
                        </form>
                    </div>
                </div>
            </div>

            {% endif %}
        </div>
    </div>
    {% endblock %}
</div>

logistic/bills/templates/bills/upload-file.html
{% extends 'base.html' %}
{% block body %}

<div class="container-fluid" id="upload-container">
    <div class="row">
        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Upload Data File</h3>
                    <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'form-template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>

                </div>

            </div>

        </div>

    </div>

</div>
{% endblock %}

logistic/bills/templates/create-file.html
{% extends 'base.html' %}
{% block body %}

<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Create Data File</h3>
                    <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'form-template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>

                </div>

            </div>

        </div>

    </div>

</div>
{% endblock %}

logistic/bills/templates/form-template.html
{% for field in form %}
    <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <span class="text-danger small">{{  fields.error}}</span>
        </div>
        <label class="control-label col-sm-2">{{ field.label_tag }}</label>
        <div class="col-sm-10">{{ field }}</div>
    </div>
{% endfor %}